# action.yml
name: 'GobletQA Tests'
description: 'Run Goblet tests in a github action'
inputs:
  test-context:
    required: false
    description: 'Path or name to the tests to run. Runs all tests if not defined'
  git-token:
    required: true
    description: 'Github Token with write access to the repository'
  goblet-token:
    required: false
    default: 'IGNORED'
    description: 'CI token from the goblet platform'
  alt-repo:
    required: false
    description: 'Alternative github repository that contains the tests to be run.'
  alt-branch:
    required: false
    description: 'Name of the branch to use for the alt repository.'
  alt-user:
    required: false
    description: 'Github user name or organization with write access to the alt repository.'
  alt-email:
    required: false
    description: 'Email of user with write access to the alt repository.'
  alt-token:
    required: false
    description: 'Github Token with write access to the alt repository.'
  test-type:
    required: false
    description: 'Type of tests to be run. Can be one of "bdd", "waypoint", or "unit". Default to "bdd"'
  test-retry:
    required: false
    description: 'Number of times a failed test should be retried'
  test-report:
    required: false
    description: 'Generate an html formatted test report for all executed tests'
  test-tracing:
    required: false
    description: 'Enabled test tracing via playwright.'
  test-record:
    required: false
    description: 'Enabled browser video recording via playwright.'
  test-screenshot:
    required: false
    description: 'Enabled browser image snapshots for failed tests. Ignored if "test-tracing" is true'
  test-timeout:
    required: false
    description: 'Amount of time for a test to wait until it times out and is then marked as failed'
  test-cache:
    required: false
    description: 'Use internal test cache when executing test'
  test-colors:
    required: false
    description: 'Force use of colors even when not a TTY'
  test-workers:
    required: false
    description: 'Number of workers to use when running tests'
  test-verbose:
    required: false
    description: 'Output verbose test results as the tests run'
  test-open-handles:
    required: false
    description: 'Detect handles left open when tests run. Forces tests to run in sync.'
  test-debug:
    required: false
    description: 'Turn on debugging for the test runner'
  browsers:
    required: false
    description: 'Comma separated list of Browsers to execute tests against'
  browser-debug:
    required: false
    description: 'Log the debug output of the playwright browser'
  browser-slow-mo:
    required: false
    description: 'Speed of actions executed in the browser while executing tests'
  browser-concurrent: 
    required: false
    description: 'Run the tests in each defined browser at the same time'
  browser-timeout:
    required: false
    description: 'Amount of time for the browser to wait until it times out and the corresponding test fails'
  artifacts-debug:
    required: false
    description: 'Enable debug logging for all generated artifacts'

outputs:
  result:
    description: 'Result of the executed Goblet tests, one of `pass` or `fail`'
  report-paths:
    description: 'Paths to the generated html test reports for each browser that ran'
  trace-paths:
    description: 'Paths of the generated playwright traces when trace is enabled'
  video-paths:
    description: 'Paths to the video recordings of executed tests when video record is enabled'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/gobletqa/goblet-tests-action:0.0.11'
  args:
    - ${{ inputs.test-context }} #1
    - ${{ inputs.git-token }} #2
    - ${{ inputs.goblet-token }} #3
    - ${{ inputs.alt-repo }} #4
    - ${{ inputs.alt-branch }} #5
    - ${{ inputs.alt-user }} #6
    - ${{ inputs.alt-email }} #7
    - ${{ inputs.alt-token }} #8
    - ${{ inputs.test-type }} #9
    - ${{ inputs.test-retry }} #10
    - ${{ inputs.test-report }} #11
    - ${{ inputs.test-tracing }} #12
    - ${{ inputs.test-screenshot }} #13
    - ${{ inputs.test-record }} #14
    - ${{ inputs.test-timeout }} #15
    - ${{ inputs.test-cache }} #16
    - ${{ inputs.test-colors }} #17
    - ${{ inputs.test-workers }} #18
    - ${{ inputs.test-verbose }} #19
    - ${{ inputs.test-open-handles }} #20
    - ${{ inputs.test-debug }} #20
    - ${{ inputs.browser }} #22
    - ${{ inputs.browser-debug }} #23
    - ${{ inputs.browser-slow-mo }} #24
    - ${{ inputs.browser-concurrent }} #25
    - ${{ inputs.browser-timeout }} #26
    - ${{ inputs.artifacts-debug }} #27
