# action.yml
name: GobletQA Tests
description: Run Goblet tests in a github action
inputs:
  test-context:
    required: false
    description: Path or name to the tests to run. Runs all tests if not defined
  git-token:
    required: true
    description: Github Token with write access to the repository
  goblet-token:
    required: true
    description: Goblet Auth Token from the goblet platform
  alt-repo:
    required: false
    description: Alternative github repository that contains the tests to be run.
  alt-branch:
    required: false
    description: Name of the branch to use for the alt repository
  alt-user:
    required: false
    description: Github user name or organization with write access to the alt repository
  alt-email:
    required: false
    description: Email of user with write access to the alt repository
  alt-token:
    required: false
    description: Github Token with write access to the alt repository
  test-type:
    required: false
    default: bdd
    description: 'Test type to run, one of `bdd`, `waypoint`, or `unit`'
  test-retry:
    required: false
    description: Number of times a failed test should be retried
  test-report:
    required: false
    description: Generate an html formatted test report for all executed tests
  test-tracing:
    required: false
    description: Enable test tracing via playwright
  test-record:
    required: false
    description: Enable browser video recording via playwright
  test-screenshot:
    required: false
    description: Enable browser snapshots on failed tests. Ignored if `test-tracing` input is `true`
  test-timeout:
    required: false
    description: Amount of time until a test times out and is marked as fail
  test-cache:
    required: false
    description: Use internal test cache when executing test
  test-colors:
    required: false
    description: Force use of colors even when not a TTY
  test-workers:
    required: false
    description: Number of workers to use when running tests
  test-verbose:
    required: false
    description: Output verbose test results as the tests run
  test-bail:
    required: false
    description: Stop running tests after a specified amount of tests fail
  browsers:
    required: false
    description: Comma separated list of Browsers to execute tests against
  browser-debug:
    required: false
    description: Log the debug output of the playwright browser
  browser-slow-mo:
    required: false
    description: Speed of actions executed in the browser while executing tests
  browser-concurrent:
    required: false
    description: Run the tests in each defined browser at the same time
  browser-timeout:
    required: false
    description: Amount of time until a browser times out and the test is marked as fail
  artifacts-debug:
    required: false
    description: Enable debug logging for all generated artifacts
  feature-tags:
    required: false
    description: Comma separated list of feature tags which determine which features are executed
  html-combine:
    required: false
    description: Combine html reports into a single file
  reuse-context:
    required: false
    description: Reuse the same browser context for each test

outputs:
  result:
    description: 'Result of the executed Goblet tests, one of `pass` or `fail`'
  report-paths:
    description: Paths to the html test reports for each browser that ran
  trace-paths:
    description: Paths of the generated playwright traces when enabled
  video-paths:
    description: Paths to the video recordings of executed tests when enabled

runs:
  using: docker
  image: 'docker://ghcr.io/gobletqa/goblet-tests-action:0.0.26'
  args:
    - ${{ inputs.test-context }} #1
    - ${{ inputs.git-token }} #2
    - ${{ inputs.goblet-token }} #3
    - ${{ inputs.alt-repo }} #4
    - ${{ inputs.alt-branch }} #5
    - ${{ inputs.alt-user }} #6
    - ${{ inputs.alt-email }} #7
    - ${{ inputs.alt-token }} #8
    - ${{ inputs.test-type }} #9
    - ${{ inputs.test-retry }} #10
    - ${{ inputs.test-report }} #11
    - ${{ inputs.test-tracing }} #12
    - ${{ inputs.test-screenshot }} #13
    - ${{ inputs.test-record }} #14
    - ${{ inputs.test-timeout }} #15
    - ${{ inputs.test-cache }} #16
    - ${{ inputs.test-colors }} #17
    - ${{ inputs.test-workers }} #18
    - ${{ inputs.test-verbose }} #19
    - ${{ inputs.test-bail }} #20
    - ${{ inputs.browsers }} #21
    - ${{ inputs.browser-slow-mo }} #22
    - ${{ inputs.browser-concurrent }} #23
    - ${{ inputs.browser-timeout }} #24
    - ${{ inputs.artifacts-debug }} #25
    - ${{ inputs.feature-tags }} #26
    - ${{ inputs.html-combine }} #27
    - ${{ inputs.reuse-context }} #28
