name: Build and Push Image
on:
  push:
    branches:
      - 'main'

jobs:
  validate-pull-request:
    name: Build - Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and Push
        run: yarn db push ci
